### ISSUE TITLE
Possible updates

### ISSUE THREAD

**Issue by vnl** [iCHAIT/oloviz#1]
Sorry for leaving a terrible title for the issue. It is really a question.

Would it be possible to help out with delivrroo.?

I am quite new to python scripting and I get a lot of cookies. Not sure which to use.

Also the data is now 1 level deep. The layout might have changed. Any chance the script could be updated if any?

#request.

**Comment by iCHAIT** [comment]
Hi @vnl 

>I get a lot of cookies. Not sure which to use.

I think when you go to the network's tab in your browser. Try to clear the tab and reload the webpage with your orders. That way you would only get the desired cookie. 

> Also the data is now 1 level deep. The layout might have changed. 

Can you share the snapshot of the new data? Or the error you are getting?

**Comment by vnl** [comment]
Sorry for the n00b questions. 
For the cookies, I followed your advice. Refreshed the page after clearing the cache and cookies. 
![image](https://user-images.githubusercontent.com/1355466/120621889-3a57db80-c456-11eb-957d-6e7a087b7f16.png)

Some screenshots to explain myself on the orders front.
![image](https://user-images.githubusercontent.com/1355466/120621348-b3a2fe80-c455-11eb-9ab4-1f81da8d37bd.png)
![Screenshot 2021-06-03 at 10 23 41](https://user-images.githubusercontent.com/1355466/120621669-febd1180-c455-11eb-9e61-18c73f534332.png)

**Comment by vnl** [comment]
A better error now...
```
▶ python3 get_deliveroo_olo.py
Traceback (most recent call last):
  File "get_deliveroo_olo.py", line 83, in <module>
    deliveroo_orders = get_deliveroo_orders(orders)
  File "get_deliveroo_olo.py", line 27, in get_deliveroo_orders
    order_entry = order_history.findAll("li")
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by iCHAIT** [comment]
Hi @vnl 

For the first part of your question. You are on the right track. When you navigate to Network's tab. You need to copy the  `orders` as a cURL command.

<img width="508" alt="Screenshot 2021-06-05 at 3 58 55 PM" src="https://user-images.githubusercontent.com/8472314/120884780-d4b34d00-c617-11eb-9d13-fd116d37ddec.png">


Then you can use [this little tool](https://curl.trillworks.com/) to convert that cURL command to python code and extract only the cookies part of it and plug it into the code.

Hope this resolves your part 1.

For part 2. I think Deliveroo has changed their HTML as a result the code I wrote no longer works. This is a major problem with scraping as the solution is not long term and sites change their layout all the time. 

To solve this you'll have to tinker a bit with the code. For eg, when I replace - 

```
order_history = soup.find("div", {"class": "user user--history mbottom30"})
```

with 

```
order_history = soup.find("div", {"class": "OrderList-59914cb140343df2"})
```

It works for me, but then I get an error somewhere down the process. Again, because the tags classes have changed.

Essentially you'll need to replace all the tag classes in the code with the new classes. I think that the hierarchy still remains the same.

**Comment by vnl** [comment]
@iCHAIT Thanks for this. Yes, the first part was fixed. I completely missed the copy as curl part. Which sorted the first part. I will, like you suggested go down the changes to do on the tags. 
I will close this issue. Thanks, again or the reply.
